In [1]:
import h5py
import numpy as np 
with h5py.File('images_training.h5','r') as H:
    data = np.copy(H['data']) 
with h5py.File('labels_training.h5','r') as H:
    label = np.copy(H['label'])

In [2]:
data.shape

(30000, 28, 28)

In [3]:
label.shape

(30000,)

In [4]:
m=data.shape[1]*data.shape[2]
data1 = data.reshape(30000,m)
del data

In [5]:
data1.shape

(30000, 784)

In [6]:
target = set()
for i in label:
    target.add(i)
d = len(list(target))
d

10

In [7]:
# ovr, label "1" vs. not label "1" 
label1 = np.array([])
for i in range(d):
    label_tmp= label
    for tmp in range(len(label_tmp)):
        if label_tmp[tmp] != i:
            label_tmp[tmp] = 0
        else:
            label_tmp[tmp] = 1
    label_tmp= label_tmp.reshape(-1,1)
    if i == 0:
        label1 = label_tmp
    else:
        label1 = np.append(label1, label_tmp, axis=1)
del label_tmp

In [8]:
label1.shape
del label

In [9]:
#used scikit-learn library, need to implemenet ourselve later
from sklearn.preprocessing import normalize
data_normalize = normalize(data1)
del data1

In [10]:
data_normalize.shape

(30000, 784)

In [11]:
#from tutorial
def logistic_loss_and_grad(weights, inputs, targets):

    #derivative of the loss function
    z = np.dot(inputs, weights)
    exp_z = np.exp(z)
    temp = -exp_z/(1 + exp_z) + targets
#     print(temp.shape, inputs.shape, (temp*inputs).shape)
#     dloss = -np.sum(temp*inputs, axis=0)[:, np.newaxis]

    testing = np.array([])
    for i in range(targets.shape[1]):
#         pass
        a4=(temp[:,i].reshape(-1,1))*inputs
#         testing = np.append(testing,np.sum(a4, axis=0))
#     dloss = testing.reshape(temp.shape[1],inputs.shape[1]).T
#     return dloss

In [12]:

# weights = np.random.random(data1.shape[1])[:, np.newaxis]
weights = np.random.rand(data_normalize.shape[1], d)
eta = 0.03
# n_iter = 2000
n_iter = 200
for epoch in range(n_iter):
    dloss = logistic_loss_and_grad(weights, data_normalize,label1 )
#     weights = weights - dloss * eta
    

MemoryError: 

In [ ]:
weights.shape

In [ ]:
def pro_function(inputs, weights):
    z = np.dot(inputs, weights)
    exp_mz = np.exp(-z)
    p = 1/(exp_mz + 1)
    return p

In [ ]:
# label1, data1
#how to deal with overflow?

result = pro_function(data1, weights)


In [ ]:
aaa = []
for i in result:
    if i >= 0.5:
        aaa.append(1)
    else:
        aaa.append(0)

In [ ]:
aaa=np.array(aaa)

In [ ]:
correct= 0
for i in range(30000):
    if aaa[i] == label1[i]:
        correct += 1
accuracy = correct / data1.shape[0]  
print("accuracy is ", round(accuracy*100, 3),"%")

In [ ]:
#used scikit-learn library, need to implemenet ourselve later
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(label1, aaa, labels= [0,1])

In [82]:
a1 = np.array([[2,3,4],[3,4,5]])
a2 = np.array([[2,3],[4,5]])

a1

array([[2, 3, 4],
       [3, 4, 5]])

In [83]:
a4=(a1[:,0].reshape(2,1))*a2
a4

array([[ 4,  6],
       [12, 15]])

In [89]:
np.sum(a4, axis=0)[:, np.newaxis]

array([[28],
       [37]])

In [91]:
testing = np.array([])
for i in range(a1.shape[1]):
    a4=(a1[:,i].reshape(-1,1))*a2
    print(a4)
    testing = np.append(testing,np.sum(a4, axis=0))
    print(testing)

[[ 4  6]
 [12 15]]
[16. 21.]
[[ 6  9]
 [16 20]]
[16. 21. 22. 29.]
[[ 8 12]
 [20 25]]
[16. 21. 22. 29. 28. 37.]


In [96]:
testing.reshape(a1.shape[1],a2.shape[1]).T

array([[16., 22., 28.],
       [21., 29., 37.]])

In [142]:
weights1 = np.random.rand(data1.shape[1], d)

In [143]:
weights1.shape

(784, 10)